(()=>{
  const BUCKET='digital-card-media', MAX_BYTES=35*1024*1024, MAX_SECONDS=30;
  const ACCEPTED=new Set(['video/mp4','video/webm']);
  let pending=null,busy=false,signedPath='',signedUrl='',lastKey='';
  const db=()=>window.__mxDb||null,c=()=>typeof state!=='undefined'?state.card:null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const notify=m=>typeof toast==='function'?toast(m):alert(m);
  const enabled=card=>['pyme','empresarial'].includes(String(card?.package||'').toLowerCase());
  const editable=()=>enabled(c())&&typeof canEditCurrentCardContent==='function'&&canEditCurrentCardContent();
  function release(){if(pending?.url)URL.revokeObjectURL(pending.url);pending=null}
  function typeOf(file){const t=String(file?.type||'').toLowerCase();if(ACCEPTED.has(t))return t;const n=String(file?.name||'').toLowerCase();if(n.endsWith('.mp4'))return'video/mp4';if(n.endsWith('.webm'))return'video/webm';return''}
  function ext(t){return t==='video/webm'?'webm':'mp4'}
  async function duration(blob){const u=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const v=document.createElement('video');const timeout=setTimeout(()=>reject(new Error('No se pudo leer la duración del video.')),12000);v.preload='metadata';v.onloadedmetadata=()=>{clearTimeout(timeout);Number.isFinite(v.duration)&&v.duration>0?resolve(v.duration):reject(new Error('Duración de video no válida.'))};v.onerror=()=>{clearTimeout(timeout);reject(new Error('El archivo no contiene un video compatible.'))};v.src=u})}finally{URL.revokeObjectURL(u)}}
  async function signed(card=c()){const d=db();if(!card?.video_url||!d){signedPath='';signedUrl='';return''}if(signedPath===card.video_url&&signedUrl)return signedUrl;const {data,error}=await d.storage.from(BUCKET).createSignedUrl(card.video_url,900);if(error||!data?.signedUrl){signedPath='';signedUrl='';return''}signedPath=card.video_url;signedUrl=data.signedUrl;return signedUrl}
  function videoHtml(url,card,preview=false){if(!url)return'';const autoplay=!!card?.video_autoplay;return `<video class="mx-card-video" src="${esc(url)}" controls playsinline preload="metadata" ${autoplay?'autoplay muted':''} style="display:block;width:100%;max-height:420px;object-fit:cover;border-radius:14px;background:#000" ${preview?'data-video-preview="1"':''}></video>${autoplay?'<div class="media-help">Autoplay inicia silenciado por política de los navegadores; el visitante puede activar el sonido.</div>':''}`}
  function editorHtml(){const card=c();if(!card)return'';if(!enabled(card))return `<section class="editor-block" id="card-video-editor-block"><div class="editor-block-header"><div><h2>Video</h2><p>Disponible en tarjetas PyME y Empresarial.</p></div></div></section>`;const url=pending?.url||signedUrl;return `<section class="editor-block" id="card-video-editor-block"><div class="editor-block-header"><div><h2>Video</h2><p>Presentación en video de hasta 30 segundos.</p></div></div><div class="editor-block-body"><div style="border:1px solid var(--line);border-radius:12px;padding:14px;display:grid;gap:12px">${url?videoHtml(url,card,true):'<div class="media-help">Todavía no hay video en esta tarjeta.</div>'}<div class="media-help">MP4 o WebM · máximo 35 MB · duración máxima 0:30. Para mejor rendimiento recomendamos MP4 H.264 optimizado para web.</div>${editable()?`<div class="field"><label for="card-video-file">Seleccionar video</label><input id="card-video-file" type="file" accept="video/mp4,video/webm,.mp4,.webm" ${!card.id||busy?'disabled':''}></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary" id="card-video-upload" type="button" ${!pending||busy?'disabled':''}>${busy?'Guardando…':'Subir video'}</button><button class="danger" id="card-video-delete" type="button" ${!card.video_url||busy?'disabled':''}>Eliminar video</button></div><label style="display:flex;gap:9px;align-items:center;font-size:13px"><input id="card-video-autoplay" type="checkbox" ${card.video_autoplay!==false?'checked':''} ${!card.video_url||busy?'disabled':''} style="width:auto"> Reproducción automática</label>`:'<div class="media-help">Tu rol o el estado de la tarjeta no permite modificar el video.</div>'}</div></div></section>`}
  function bind(){const f=document.getElementById('card-video-file');if(f)f.onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const t=typeOf(file);if(!t)return notify('Formato no permitido. Usa MP4 o WebM.');if(file.size>MAX_BYTES)return notify('El video supera el límite de 35 MB.');try{const d=await duration(file);if(d>MAX_SECONDS+.5)return notify(`El video dura ${Math.ceil(d)} segundos. El máximo es 30.`);release();pending={blob:file,type:t,extension:ext(t),duration:Math.max(1,Math.ceil(d)),url:URL.createObjectURL(file)};renderBlock()}catch(err){notify(err.message||'No se pudo procesar el video.')}};const u=document.getElementById('card-video-upload');if(u)u.onclick=upload;const del=document.getElementById('card-video-delete');if(del)del.onclick=remove;const a=document.getElementById('card-video-autoplay');if(a)a.onchange=()=>saveAutoplay(a.checked)}
  function renderBlock(){if(typeof state==='undefined'||state.page!=='editor')return;const host=document.querySelector('.editor-sections');if(!host)return;const old=document.getElementById('card-video-editor-block');if(old)old.outerHTML=editorHtml();else host.insertAdjacentHTML('beforeend',editorHtml());bind()}
  async function ensure(){if(typeof state==='undefined'||state.page!=='editor')return;const host=document.querySelector('.editor-sections');if(!host)return;const card=c(),key=String(card?.id||'new');if(key!==lastKey){release();signedPath='';signedUrl='';lastKey=key}if(card?.video_url)await signed(card);if(!document.getElementById('card-video-editor-block'))renderBlock()}
  async function upload(){const card=c(),d=db();if(!pending||!card?.id||!d||busy||!editable())return;busy=true;renderBlock();const old=card.video_url||null,path=`${card.owner_id||state.session?.user?.id}/${card.id}/video/${crypto.randomUUID()}.${pending.extension}`;const {error:up}=await d.storage.from(BUCKET).upload(path,pending.blob,{contentType:pending.type,cacheControl:'3600',upsert:false});if(up){busy=false;renderBlock();return notify('No se pudo subir el video: '+up.message)}const {data,error}=await d.rpc('set_card_video_reference',{target_card_id:card.id,object_path:path,duration_seconds:pending.duration,autoplay_enabled:card.video_autoplay!==false});if(error){await d.storage.from(BUCKET).remove([path]);busy=false;renderBlock();return notify('No se pudo guardar el video: '+error.message)}const row=Array.isArray(data)?data[0]:data;if(row?.id)Object.assign(card,row);release();signedPath='';signedUrl='';if(old&&old!==path)await d.storage.from(BUCKET).remove([old]);busy=false;await signed(card);renderBlock();if(typeof refreshPreview==='function')refreshPreview();notify('Video actualizado correctamente.')}
  async function saveAutoplay(value){const card=c(),d=db();if(!card?.id||!card.video_url||!d||busy)return;busy=true;const {data,error}=await d.rpc('set_card_video_reference',{target_card_id:card.id,object_path:card.video_url,duration_seconds:Number(card.video_duration_seconds),autoplay_enabled:!!value});busy=false;if(error){renderBlock();return notify('No se pudo actualizar autoplay: '+error.message)}const row=Array.isArray(data)?data[0]:data;if(row?.id)Object.assign(card,row);renderBlock();notify(value?'Autoplay activado.':'Autoplay desactivado.')}
  async function remove(){const card=c(),d=db();if(!card?.id||!card.video_url||!d||busy)return;if(!confirm('¿Eliminar el video de esta tarjeta?'))return;busy=true;const old=card.video_url,{data,error}=await d.rpc('set_card_video_reference',{target_card_id:card.id,object_path:null,duration_seconds:null,autoplay_enabled:true});if(error){busy=false;renderBlock();return notify('No se pudo eliminar el video: '+error.message)}const row=Array.isArray(data)?data[0]:data;if(row?.id)Object.assign(card,row);signedPath='';signedUrl='';await d.storage.from(BUCKET).remove([old]);busy=false;renderBlock();if(typeof refreshPreview==='function')refreshPreview();notify('Video eliminado correctamente.')}
  async function injectPublic(){if(typeof state==='undefined'||!location.pathname.startsWith('/c/'))return;const card=state.publicCard;if(!enabled(card)||!card?.video_url)return;const d=db();if(!d)return;const {data,error}=await d.storage.from(BUCKET).createSignedUrl(card.video_url,900);if(error||!data?.signedUrl)return;const main=document.querySelector('.digital-card-surface .card-content');if(!main||main.querySelector('[data-public-video]'))return;const section=document.createElement('section');section.className='card-section';section.dataset.publicVideo='1';section.innerHTML=`<h2 class="card-section-title">Video</h2>${videoHtml(data.signedUrl,card,false)}`;const actions=main.querySelector('.card-main-actions');if(actions)actions.insertAdjacentElement('afterend',section);else main.prepend(section)}
  let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;void ensure();void injectPublic()})});observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{void ensure();void injectPublic()});else{void ensure();void injectPublic()}
})();