(()=>{
  const BUCKET='digital-card-media',MAX_BYTES=35*1024*1024,MAX_SECONDS=30,ACCEPTED=new Set(['video/mp4','video/webm']);
  let pending=null,busy=false,signedPath='',signedUrl='',lastKey='';
  const db=()=>window.__mxDb||null,c=()=>typeof state!=='undefined'?state.card:null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const notify=m=>typeof toast==='function'?toast(m):alert(m),enabled=card=>['pyme','empresarial'].includes(String(card?.package||'').toLowerCase()),editable=()=>enabled(c())&&typeof canEditCurrentCardContent==='function'&&canEditCurrentCardContent();
  const placement=card=>card?.video_placement==='cover'?'cover':'section';
  function release(){if(pending?.url)URL.revokeObjectURL(pending.url);pending=null}
  function typeOf(file){const t=String(file?.type||'').toLowerCase(),n=String(file?.name||'').toLowerCase();return ACCEPTED.has(t)?t:n.endsWith('.mp4')?'video/mp4':n.endsWith('.webm')?'video/webm':''}
  async function duration(blob){const u=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const v=document.createElement('video'),timer=setTimeout(()=>reject(new Error('No se pudo leer la duración del video.')),12000);v.preload='metadata';v.onloadedmetadata=()=>{clearTimeout(timer);Number.isFinite(v.duration)&&v.duration>0?resolve(v.duration):reject(new Error('Duración de video no válida.'))};v.onerror=()=>{clearTimeout(timer);reject(new Error('El archivo no contiene un video compatible.'))};v.src=u})}finally{URL.revokeObjectURL(u)}}
  async function signed(card=c()){const d=db();if(!card?.video_url||!d){signedPath='';signedUrl='';return''}if(signedPath===card.video_url&&signedUrl)return signedUrl;const {data,error}=await d.storage.from(BUCKET).createSignedUrl(card.video_url,900);if(error||!data?.signedUrl)return'';signedPath=card.video_url;signedUrl=data.signedUrl;return signedUrl}
  function videoTag(url,card,cover=false){const auto=!!card.video_autoplay,loop=!!card.video_loop,poster=cover&&card.coverSignedUrl?` poster="${esc(card.coverSignedUrl)}"`:'';return `<video class="mx-card-video${cover?' mx-card-video-cover':''}" src="${esc(url)}" controls playsinline preload="metadata"${poster} ${auto?'autoplay muted':''} ${loop?'loop':''} style="display:block;width:100%;${cover?'height:100%;min-height:inherit;object-fit:cover':'max-height:420px;object-fit:cover;border-radius:14px'};background:#000"></video>`}
  function editorHtml(){const card=c();if(!card)return'';if(!enabled(card))return `<section class="editor-block" id="card-video-editor-block"><div class="editor-block-header"><div><h2>Video</h2><p>Disponible en tarjetas PyME y Empresarial.</p></div></div></section>`;const url=pending?.url||signedUrl,p=placement(card);return `<section class="editor-block" id="card-video-editor-block"><div class="editor-block-header"><div><h2>Video</h2><p>Presentación en video de hasta 30 segundos.</p></div></div><div class="editor-block-body"><div style="border:1px solid var(--line);border-radius:12px;padding:14px;display:grid;gap:12px">${url?videoTag(url,card):'<div class="media-help">Todavía no hay video en esta tarjeta.</div>'}<div class="media-help">MP4 o WebM · máximo 35 MB · duración máxima 0:30.</div>${editable()?`<div class="field"><label for="card-video-file">Seleccionar video</label><input id="card-video-file" type="file" accept="video/mp4,video/webm,.mp4,.webm" ${!card.id||busy?'disabled':''}></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary" id="card-video-upload" type="button" ${!pending||busy?'disabled':''}>${busy?'Guardando…':'Subir video'}</button><button class="danger" id="card-video-delete" type="button" ${!card.video_url||busy?'disabled':''}>Eliminar video</button></div><div class="field"><label for="card-video-placement">Ubicación del video</label><select id="card-video-placement" ${!card.video_url||busy?'disabled':''}><option value="section" ${p==='section'?'selected':''}>Sección de video</option><option value="cover" ${p==='cover'?'selected':''}>Sustituir portada</option></select><small class="media-help">Si sustituye la portada, no se repite en la sección Video.</small></div><label style="display:flex;gap:9px;align-items:center"><input id="card-video-autoplay" type="checkbox" ${card.video_autoplay!==false?'checked':''} ${!card.video_url||busy?'disabled':''} style="width:auto"> Reproducción automática</label><label style="display:flex;gap:9px;align-items:center"><input id="card-video-loop" type="checkbox" ${card.video_loop?'checked':''} ${!card.video_url||busy?'disabled':''} style="width:auto"> Repetir en bucle</label>`:'<div class="media-help">Tu rol o estado no permite modificar el video.</div>'}</div></div></section>`}
  function bind(){const f=document.getElementById('card-video-file');if(f)f.onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const t=typeOf(file);if(!t)return notify('Formato no permitido. Usa MP4 o WebM.');if(file.size>MAX_BYTES)return notify('El video supera 35 MB.');try{const d=await duration(file);if(d>MAX_SECONDS+.5)return notify(`El video dura ${Math.ceil(d)} segundos. El máximo es 30.`);release();pending={blob:file,type:t,extension:t==='video/webm'?'webm':'mp4',duration:Math.max(1,Math.ceil(d)),url:URL.createObjectURL(file)};renderBlock()}catch(err){notify(err.message)}};document.getElementById('card-video-upload')?.addEventListener('click',upload);document.getElementById('card-video-delete')?.addEventListener('click',remove);const a=document.getElementById('card-video-autoplay'),l=document.getElementById('card-video-loop'),p=document.getElementById('card-video-placement');if(a)a.onchange=()=>saveSettings(a.checked,!!c()?.video_loop,placement(c()),'Autoplay');if(l)l.onchange=()=>saveSettings(c()?.video_autoplay!==false,l.checked,placement(c()),'Bucle');if(p)p.onchange=()=>saveSettings(c()?.video_autoplay!==false,!!c()?.video_loop,p.value,'Ubicación')}
  function renderBlock(){if(typeof state==='undefined'||state.page!=='editor')return;const host=document.querySelector('.editor-sections');if(!host)return;const old=document.getElementById('card-video-editor-block');if(old)old.outerHTML=editorHtml();else host.insertAdjacentHTML('beforeend',editorHtml());bind()}
  async function ensure(){if(typeof state==='undefined'||state.page!=='editor')return;const host=document.querySelector('.editor-sections');if(!host)return;const card=c(),key=String(card?.id||'new');if(key!==lastKey){release();signedPath='';signedUrl='';lastKey=key}if(card?.video_url)await signed(card);if(!document.getElementById('card-video-editor-block'))renderBlock()}
  async function rpc(card,path,dur,auto,loop,p){return db().rpc('set_card_video_reference',{target_card_id:card.id,object_path:path,duration_seconds:dur,autoplay_enabled:!!auto,loop_enabled:!!loop,placement:p})}
  async function upload(){const card=c(),d=db();if(!pending||!card?.id||!d||busy||!editable())return;busy=true;renderBlock();const old=card.video_url||null,path=`${card.owner_id||state.session?.user?.id}/${card.id}/video/${crypto.randomUUID()}.${pending.extension}`,{error:up}=await d.storage.from(BUCKET).upload(path,pending.blob,{contentType:pending.type,cacheControl:'3600',upsert:false});if(up){busy=false;renderBlock();return notify('No se pudo subir el video: '+up.message)}const {data,error}=await rpc(card,path,pending.duration,card.video_autoplay!==false,!!card.video_loop,placement(card));if(error){await d.storage.from(BUCKET).remove([path]);busy=false;renderBlock();return notify('No se pudo guardar el video: '+error.message)}Object.assign(card,Array.isArray(data)?data[0]:data);release();signedPath='';signedUrl='';if(old&&old!==path)await d.storage.from(BUCKET).remove([old]);busy=false;await signed(card);renderBlock();notify('Video actualizado correctamente.')}
  async function saveSettings(auto,loop,p,label){const card=c();if(!card?.id||!card.video_url||busy)return;busy=true;const {data,error}=await rpc(card,card.video_url,Number(card.video_duration_seconds),auto,loop,p);busy=false;if(error){renderBlock();return notify('No se pudo actualizar el video: '+error.message)}Object.assign(card,Array.isArray(data)?data[0]:data);renderBlock();notify(label+' actualizado correctamente.')}
  async function remove(){const card=c(),d=db();if(!card?.id||!card.video_url||busy||!confirm('¿Eliminar el video de esta tarjeta?'))return;busy=true;const old=card.video_url,{data,error}=await rpc(card,null,null,true,false,'section');if(error){busy=false;renderBlock();return notify(error.message)}Object.assign(card,Array.isArray(data)?data[0]:data);signedPath='';signedUrl='';await d.storage.from(BUCKET).remove([old]);busy=false;renderBlock();notify('Video eliminado correctamente.')}
  async function injectPublic(){if(typeof state==='undefined'||!location.pathname.startsWith('/c/'))return;const card=state.publicCard;if(!enabled(card)||!card?.video_url)return;const d=db();if(!d)return;const {data,error}=await d.storage.from(BUCKET).createSignedUrl(card.video_url,900);if(error||!data?.signedUrl)return;document.querySelectorAll('[data-public-video]').forEach(el=>el.remove());if(placement(card)==='cover'){const cover=document.querySelector('.digital-card-surface .card-cover');if(!cover||cover.dataset.videoCover==='1')return;cover.dataset.videoCover='1';cover.style.backgroundImage='none';[...cover.children].forEach(child=>{if(!child.classList.contains('hero-logo'))child.remove()});cover.insertAdjacentHTML('afterbegin',videoTag(data.signedUrl,card,true));const logo=cover.querySelector('.hero-logo');if(logo)logo.style.zIndex='2';return}const main=document.querySelector('.digital-card-surface .card-content');if(!main)return;const section=document.createElement('section');section.className='card-section';section.dataset.publicVideo='1';section.innerHTML=`<h2 class="card-section-title">Video</h2>${videoTag(data.signedUrl,card)}`;const actions=main.querySelector('.card-main-actions');actions?actions.insertAdjacentElement('afterend',section):main.prepend(section)}
  let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;void ensure();void injectPublic()})});observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{void ensure();void injectPublic()});else{void ensure();void injectPublic()}
})();