(()=>{
  'use strict';
  if(window.__mxRewardsInstalled)return;
  window.__mxRewardsInstalled=true;

  const lang=()=>{try{return typeof language!=='undefined'?language:'es'}catch{return 'es'}};
  const t=(es,en)=>lang()==='en'?en:es;
  const money=(value,currency='MXN')=>new Intl.NumberFormat(lang()==='en'?'en-US':'es-MX',{style:'currency',currency:currency||'MXN',maximumFractionDigits:2}).format(Number(value||0));
  const dateText=value=>value?new Intl.DateTimeFormat(lang()==='en'?'en-US':'es-MX',{dateStyle:'medium'}).format(new Date(value)):'—';
  const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const statusLabel=status=>({pending:t('Pendiente','Pending'),available:t('Disponible','Available'),redeemed:t('Utilizado','Redeemed'),reversed:t('Revertido','Reversed'),expired:t('Vencido','Expired')})[status]||status;
  const stateSafe=()=>{try{return typeof state!=='undefined'?state:null}catch{return null}};

  function installStyles(){
    if(document.getElementById('mx-rewards-style'))return;
    const style=document.createElement('style');
    style.id='mx-rewards-style';
    style.textContent=`
      .rewards-summary{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px;margin:16px 0 20px}
      .reward-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:16px;box-shadow:var(--shadow-surface)}
      .reward-card span{display:block;color:var(--muted);font-size:12px;margin-bottom:6px}.reward-card b{font-size:24px}
      .rewards-help{margin:0 0 18px;color:var(--muted);font-size:13px;line-height:1.5}
      .reward-status{display:inline-block;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:700;background:#eef2ff;color:#4f46e5}
      .reward-status.available{background:#eaf8f0;color:#087d3e}.reward-status.redeemed{background:#eef2f6;color:#475467}.reward-status.reversed,.reward-status.expired{background:#fff0f2;color:#b42318}
      .rewards-empty{padding:34px 18px;text-align:center;color:var(--muted)}
      .rewards-nav-icon{display:inline-block;width:22px;text-align:center}
      @media(max-width:900px){.rewards-summary{grid-template-columns:repeat(2,1fr)}}
      @media(max-width:600px){.rewards-summary{grid-template-columns:1fr}.rewards-table-wrap{overflow-x:auto}}
    `;
    document.head.appendChild(style);
  }

  async function loadRewards(){
    if(typeof db==='undefined')throw new Error('db unavailable');
    const [{data:ledger,error:ledgerError},{data:sales,error:salesError}]=await Promise.all([
      db.from('reward_ledger').select('id,referral_sale_id,source_card_id,amount,currency,status,available_at,redeemed_at,reversed_at,reason,created_at').order('created_at',{ascending:false}).limit(100),
      db.from('referral_sales').select('id,product_name_snapshot,payment_status,reward_amount_snapshot,currency,created_at,paid_at').order('created_at',{ascending:false}).limit(100)
    ]);
    if(ledgerError)throw ledgerError;
    if(salesError)throw salesError;
    const saleMap=new Map((sales||[]).map(s=>[s.id,s]));
    return {ledger:ledger||[],saleMap};
  }

  function totals(rows,status){return rows.filter(r=>r.status===status).reduce((sum,r)=>sum+Number(r.amount||0),0)}

  async function renderRewards(){
    installStyles();
    const main=document.querySelector('.main');
    if(!main)return;
    const s=stateSafe();
    if(s)s.page='rewards';
    main.innerHTML=`<div class="top"><div><h1>${t('Mis recompensas','My rewards')}</h1><p>${t('Consulta el saldo generado por clientes que llegaron a OMLIG desde tus tarjetas.','See rewards generated by customers referred to OMLIG from your cards.')}</p></div></div><div class="panel"><div class="rewards-empty">${t('Cargando recompensas…','Loading rewards…')}</div></div>`;
    try{
      const {ledger,saleMap}=await loadRewards();
      const currency=ledger.find(r=>r.currency)?.currency||'MXN';
      const rows=ledger.map(row=>{const sale=saleMap.get(row.referral_sale_id)||{};return `<tr><td>${esc(sale.product_name_snapshot||t('Producto OMLIG','OMLIG product'))}</td><td>${dateText(row.created_at)}</td><td>${money(row.amount,row.currency||currency)}</td><td><span class="reward-status ${esc(row.status)}">${esc(statusLabel(row.status))}</span></td></tr>`}).join('');
      main.innerHTML=`
        <div class="top"><div><h1>${t('Mis recompensas','My rewards')}</h1><p>${t('Consulta el saldo generado por clientes que llegaron a OMLIG desde tus tarjetas.','See rewards generated by customers referred to OMLIG from your cards.')}</p></div></div>
        <p class="rewards-help">${t('Las recompensas aparecen como pendientes hasta que OMLIG valida el pago. Una vez disponibles pueden aplicarse a servicios elegibles.','Rewards remain pending until OMLIG validates payment. Once available, they can be applied to eligible services.')}</p>
        <div class="rewards-summary">
          <div class="reward-card"><span>${t('Pendiente','Pending')}</span><b>${money(totals(ledger,'pending'),currency)}</b></div>
          <div class="reward-card"><span>${t('Disponible','Available')}</span><b>${money(totals(ledger,'available'),currency)}</b></div>
          <div class="reward-card"><span>${t('Utilizado','Redeemed')}</span><b>${money(totals(ledger,'redeemed'),currency)}</b></div>
          <div class="reward-card"><span>${t('Revertido / vencido','Reversed / expired')}</span><b>${money(totals(ledger,'reversed')+totals(ledger,'expired'),currency)}</b></div>
        </div>
        <div class="panel"><h2 style="margin-top:0">${t('Historial','History')}</h2>${rows?`<div class="rewards-table-wrap"><table class="table"><thead><tr><th>${t('Producto','Product')}</th><th>${t('Fecha','Date')}</th><th>${t('Recompensa','Reward')}</th><th>${t('Estado','Status')}</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="rewards-empty">${t('Aún no tienes recompensas registradas. Cuando una venta referida sea validada aparecerá aquí.','You do not have any rewards yet. Validated referred sales will appear here.')}</div>`}</div>`;
      installDesktopNav();
    }catch(error){
      console.error('Rewards load failed',error);
      main.innerHTML=`<div class="top"><div><h1>${t('Mis recompensas','My rewards')}</h1></div></div><div class="panel"><div class="error">${t('No se pudieron cargar tus recompensas. Intenta nuevamente.','Your rewards could not be loaded. Please try again.')}</div></div>`;
    }
  }

  function installDesktopNav(){
    const nav=document.querySelector('.nav');
    if(!nav||nav.querySelector('[data-mx-rewards-nav]'))return;
    const button=document.createElement('button');
    button.dataset.mxRewardsNav='1';
    button.className=stateSafe()?.page==='rewards'?'active':'';
    button.innerHTML=`<span class="rewards-nav-icon" aria-hidden="true">★</span><span>${t('Mis recompensas','My rewards')}</span>`;
    button.addEventListener('click',()=>{void renderRewards()});
    nav.appendChild(button);
  }

  function installGoHook(){
    if(typeof window.go!=='function'||window.__mxRewardsGoHook)return false;
    window.__mxRewardsGoHook=true;
    const original=window.go;
    window.go=function(page,...args){if(page==='rewards'){void renderRewards();return;}return original.call(this,page,...args)};
    return true;
  }

  function installMobileHook(){
    if(typeof window.mobileNavigation!=='function'||window.__mxRewardsMobileHook)return false;
    window.__mxRewardsMobileHook=true;
    const original=window.mobileNavigation;
    window.mobileNavigation=function(){
      const html=original();
      if(/go\('rewards'\)/.test(html))return html;
      const button=`<button class="${stateSafe()?.page==='rewards'?'active':''}" onclick="go('rewards')"><span aria-hidden="true">★</span><span>${t('Recompensas','Rewards')}</span></button>`;
      return html+button;
    };
    return true;
  }

  installStyles();installDesktopNav();installGoHook();installMobileHook();
  let scheduled=false;
  new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;installDesktopNav();installGoHook();installMobileHook();if(stateSafe()?.page==='rewards'&&!document.querySelector('.rewards-summary'))void renderRewards();});}).observe(document.documentElement,{childList:true,subtree:true});
})();
